name: Main examples
# run-name: by @${{ github.actor }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      example:
        description: list of examples
        type: choice
        options:
          - default
          - all




jobs:
  default:
    name: Default cluster
    if: contains(fromJson('["all", "default"]'), inputs.example) || ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/reuse-test-clusters.yaml
    with:
      pulumi-stack: basic
    secrets:
      google-credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      hcloud-token: ${{ secrets.HCLOUD_TOKEN }}
