name: Pulumi
run-name: Deploy cluster @${{ github.actor }}

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: preview
    runs-on: ubuntu-latest
    env:
      PULUMI_STACK: basic
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Setup Go ✨
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Downloading dependencies 📦
        run: go mod download
      - name: Install pulumi cli
        uses: pulumi/actions@v4
      - name: Create a stack
        run: make ci-pulumi-prepare
        env:
          PULUMI_STACK_INIT_FLAGS: --secrets-provider=gcpkms://projects/spigell-infra/locations/global/keyRings/spigell-infra-keyring/cryptoKeys/spigell-infra-phkh-pulumi-key
          PULUMI_BACKEND: gs://spigell-infra-phkh-pulumi-states
          HCLOUD_IMAGE: '133426649'
      - uses: pulumi/actions@v4
        name: Preview
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK }}
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      - uses: pulumi/actions@v4
        name: Up
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK }}
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      - name: Reachability check
        run: make pulumi-tests
      - name: Cleanup
        if: always()
        uses: pulumi/actions@v4
        with:
          command: destroy
          stack-name: ${{ env.PULUMI_STACK }}
          remove: true
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
